#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

currentBranch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$currentBranch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

docker run -u node --rm -v $PWD/:/home/node/app -w /home/node/app node:18.15-alpine3.17 sh -c 'npm i -g pnpm ; [ ! -d ./node_modules ] && pnpm install ; pnpm run package'