name: CI
on: [push]
permissions:
    contents: read # to fetch code (actions/checkout)
jobs:
    Lint:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2.2.4
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: pnpm
            - run: 'pnpm i && pnpm run sync && pnpm run package && pnpm run lint'
