name: Release

on:
    push:
        branches:
            - 'main'
        paths:
            - 'packages/sti/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Build & Publish @dev Release
        if: github.repository == 'gyurielf/mono-sti'
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                  # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
                  fetch-depth: 0

            - name: Use PNPM v8
              uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Setup Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            # PNPM Store cache setup
            - name: Get pnpm store directory
              id: pnpm-cache
              run: |
                  echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
            - name: Setup pnpm cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install

            - name: Bump version to release
              run: node scripts/dev-version.js

            - name: Packaging
              run: pnpm ci:package

            - name: Creating .npmrc
              run: |
                  cat << EOF > "$HOME/.npmrc"
                    //registry.npmjs.org/:_authToken=$NPM_TOKEN
                  EOF
                  pnpm publish packages/sti --access public --tag main --no-git-checks
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
